#%RAML 1.0
title: Interface between publishers and printers for describing print products
version: v1
baseUri: https://api.ipe.example/{version}
securitySchemes:
  default: !include security.raml

types:
  Product: !include types/product.raml
  Component: !include types/component.raml
  Finishing: !include types/finishing.raml
  FinishingProperty: !include types/finishing_property.raml

/products:
  get:
    responses:
      200:
        body:
          application/json:
            type: Product
  post:
    responses:
      201:
        body:
          application/json:
            type: Product

  /{product_id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Product
