#%RAML 1.0 DataType
type: object
displayName: A finishing
properties:
  id:
    type: integer
    example: 1337
    description: The object ID of the finishing
  type:
    type: string
    example: laminating
    description: |
      The type of the finshing as described in the standard document
    enum:
      - laminating
      - foil_stamp
      - debossing
      - embossing
  created_at:
    type: datetime
    example: 2017-09-11T08:45:00+02:00
    description: |
      The date on which this record was created.
  updated_at:
    type: datetime
    example: 2017-09-11T08:45:00+02:00
    description: |
      The date on which this record was last updated.
